server:
  port: 12000
spring:
  application:
      name: tensquare-config
  cloud:
      config:
        server:
          git:
            uri: https://gitee.com/MaHais/configs.git
  rabbitmq:
    host: 192.168.25.131

management:
  endpoints:
    web:
      exposure:
        exclude: bus-refresh